export const customers = [
    {
        id: 1,
        Country: "USA",
        CMShortCode: "US",
        InvoiceName: "John Doe",
        Address: "123 Main St",
        Phone: "555-1234",
        Email: "john.doe@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Jane Smith",
        ConsigneeAddress: "456 Elm St",
        ConsgineePhone: "555-5678",
        ConsgineeEmail: "jane.smith@example.com",
        DHLAddress: "789 Oak St",
        Action: "Edit"
    },
    {
        id: 2,
        Country: "Canada",
        CMShortCode: "CA",
        InvoiceName: "Alice Johnson",
        Address: "456 Maple Ave",
        Phone: "555-4321",
        Email: "alice.johnson@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Bob Brown",
        ConsigneeAddress: "789 Pine St",
        ConsgineePhone: "555-8765",
        ConsgineeEmail: "bob.brown@example.com",
        DHLAddress: "123 Cedar St",
        Action: "Delete"
    },
    {
        id: 3,
        Country: "UK",
        CMShortCode: "UK",
        InvoiceName: "Mary Wilson",
        Address: "789 High St",
        Phone: "555-7890",
        Email: "mary.wilson@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Tom Green",
        ConsigneeAddress: "321 Low St",
        ConsgineePhone: "555-2345",
        ConsgineeEmail: "tom.green@example.com",
        DHLAddress: "456 Broad St",
        Action: "Edit"
    },
    {
        id: 4,
        Country: "Germany",
        CMShortCode: "DE",
        InvoiceName: "Hans Schmidt",
        Address: "654 Berlin Strasse",
        Phone: "555-6789",
        Email: "hans.schmidt@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Greta Müller",
        ConsigneeAddress: "987 Munich Platz",
        ConsgineePhone: "555-3456",
        ConsgineeEmail: "greta.muller@example.com",
        DHLAddress: "321 Hamburg Allee",
        Action: "Delete"
    },
    {
        id: 5,
        Country: "France",
        CMShortCode: "FR",
        InvoiceName: "Pierre Dupont",
        Address: "753 Paris Rue",
        Phone: "555-2468",
        Email: "pierre.dupont@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Marie Leclerc",
        ConsigneeAddress: "159 Lyon Boulevard",
        ConsgineePhone: "555-7890",
        ConsgineeEmail: "marie.leclerc@example.com",
        DHLAddress: "357 Marseille Avenue",
        Action: "Edit"
    },
    {
        id: 6,
        Country: "Italy",
        CMShortCode: "IT",
        InvoiceName: "Giuseppe Rossi",
        Address: "852 Rome Via",
        Phone: "555-1357",
        Email: "giuseppe.rossi@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Maria Russo",
        ConsigneeAddress: "753 Milan Piazza",
        ConsgineePhone: "555-2468",
        ConsgineeEmail: "maria.russo@example.com",
        DHLAddress: "951 Naples Strada",
        Action: "Delete"
    },
    {
        id: 7,
        Country: "Spain",
        CMShortCode: "ES",
        InvoiceName: "Juan García",
        Address: "369 Madrid Calle",
        Phone: "555-3691",
        Email: "juan.garcia@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Ana López",
        ConsigneeAddress: "258 Barcelona Avenida",
        ConsgineePhone: "555-1478",
        ConsgineeEmail: "ana.lopez@example.com",
        DHLAddress: "147 Valencia Plaza",
        Action: "Edit"
    },
    {
        id: 8,
        Country: "Australia",
        CMShortCode: "AU",
        InvoiceName: "Jack Smith",
        Address: "147 Sydney Street",
        Phone: "555-9514",
        Email: "jack.smith@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Emily Brown",
        ConsigneeAddress: "369 Melbourne Avenue",
        ConsgineePhone: "555-3691",
        ConsgineeEmail: "emily.brown@example.com",
        DHLAddress: "258 Brisbane Road",
        Action: "Delete"
    },
    {
        id: 9,
        Country: "Japan",
        CMShortCode: "JP",
        InvoiceName: "Takashi Yamamoto",
        Address: "369 Tokyo Lane",
        Phone: "555-2587",
        Email: "takashi.yamamoto@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Yuko Suzuki",
        ConsigneeAddress: "147 Osaka Boulevard",
        ConsgineePhone: "555-9514",
        ConsgineeEmail: "yuko.suzuki@example.com",
        DHLAddress: "369 Nagoya Street",
        Action: "Edit"
    },
    {
        id: 10,
        Country: "Brazil",
        CMShortCode: "BR",
        InvoiceName: "Carlos Silva",
        Address: "258 Rio de Janeiro Rua",
        Phone: "555-7412",
        Email: "carlos.silva@example.com",
        SupplierName: "Jane Smith",
        SupplierAddress: "456 Elm St",
        SupplierPhone: "555-5678",
        SupplierEmail: "jane.smith@example.com",
        ConsigneeName: "Ana Costa",
        ConsigneeAddress: "963 São Paulo Avenida",
        ConsgineePhone: "555-8524",
        ConsgineeEmail: "ana.costa@example.com",
        DHLAddress: "741 Brasília Praça",
        Action: "Delete"
    }
]