export const paymentList = [
    {
      id: 1,
      image:'/assets/images/cars/1.jpg',
      IncomeDate: "04-01-2024",
      Remitter: "John Doe",
      Customer: "Company A",
      AmountReceived: 1000,
      AmountPerTTCopy: 500,
      BankCharges: 50,
      TTDate: "03-31-2024",
      RefNumberAndLink: "123456",
      Message: "Payment for services",
      InternalMemo: "Process immediately",
      ExchangeRate: 1.2
    },
    {
      id: 2,
      image:'/assets/images/cars/2.jpg',
      IncomeDate: "04-02-2024",
      Remitter: "Jane Smith",
      Customer: "Company B",
      AmountReceived: 1500,
      AmountPerTTCopy: 750,
      BankCharges: 75,
      TTDate: "04-01-2024",
      RefNumberAndLink: "234567",
      Message: "Payment for goods",
      InternalMemo: "Check for authenticity",
      ExchangeRate: 1.25
    },
    {
      id: 3,
      image:'/assets/images/cars/3.jpg',
      IncomeDate: "04-03-2024",
      Remitter: "Alice Johnson",
      Customer: "Company C",
      AmountReceived: 2000,
      AmountPerTTCopy: 1000,
      BankCharges: 100,
      TTDate: "04-02-2024",
      RefNumberAndLink: "345678",
      Message: "Reimbursement for expenses",
      InternalMemo: "Verify supporting documents",
      ExchangeRate: 1.3
    },
    {
      id: 4,
      image:'/assets/images/cars/4.jpg',
      IncomeDate: "04-04-2024",
      Remitter: "Bob Williams",
      Customer: "Company D",
      AmountReceived: 2500,
      AmountPerTTCopy: 1250,
      BankCharges: 125,
      TTDate: "04-03-2024",
      RefNumberAndLink: "456789",
      Message: "Payment for services rendered",
      InternalMemo: "Check for tax compliance",
      ExchangeRate: 1.35
    },
    {
      id: 5,
      image:'/assets/images/cars/5.jpg',
      IncomeDate: "04-05-2024",
      Remitter: "Eve Brown",
      Customer: "Company E",
      AmountReceived: 3000,
      AmountPerTTCopy: 1500,
      BankCharges: 150,
      TTDate: "04-04-2024",
      RefNumberAndLink: "567890",
      Message: "Refund for overpayment",
      InternalMemo: "Credit to customer account",
      ExchangeRate: 1.4
    },
    {
      id: 6,
      image:'/assets/images/cars/6.jpg',
      IncomeDate: "04-06-2024",
      Remitter: "Charlie Davis",
      Customer: "Company F",
      AmountReceived: 3500,
      AmountPerTTCopy: 1750,
      BankCharges: 175,
      TTDate: "04-05-2024",
      RefNumberAndLink: "678901",
      Message: "Payment for goods delivered",
      InternalMemo: "Confirm receipt of goods",
      ExchangeRate: 1.45
    },
    {
      id: 7,
      image:'/assets/images/cars/7.jpg',
      IncomeDate: "04-07-2024",
      Remitter: "Grace Wilson",
      Customer: "Company G",
      AmountReceived: 4000,
      AmountPerTTCopy: 2000,
      BankCharges: 200,
      TTDate: "04-06-2024",
      RefNumberAndLink: "789012",
      Message: "Payment for services rendered",
      InternalMemo: "Cross-check with contract terms",
      ExchangeRate: 1.5
    },
    {
      id: 8,
      image:'/assets/images/cars/3.jpg',
      IncomeDate: "04-08-2024",
      Remitter: "David Lee",
      Customer: "Company H",
      AmountReceived: 4500,
      AmountPerTTCopy: 2250,
      BankCharges: 225,
      TTDate: "04-07-2024",
      RefNumberAndLink: "890123",
      Message: "Reimbursement for travel expenses",
      InternalMemo: "Approve after verification",
      ExchangeRate: 1.55
    },
    {
      id: 9,
      image:'/assets/images/cars/2.jpg',
      IncomeDate: "04-09-2024",
      Remitter: "Sarah Miller",
      Customer: "Company I",
      AmountReceived: 5000,
      AmountPerTTCopy: 2500,
      BankCharges: 250,
      TTDate: "04-08-2024",
      RefNumberAndLink: "901234",
      Message: "Payment for consulting services",
      InternalMemo: "Check for project completion",
      ExchangeRate: 1.6
    },
    {
      id: 10,
      image:'/assets/images/cars/1.jpg',
      IncomeDate: "04-10-2024",
      Remitter: "Peter Brown",
      Customer: "Company J",
      AmountReceived: 5500,
      AmountPerTTCopy: 2750,
      BankCharges: 275,
      TTDate: "04-09-2024",
      RefNumberAndLink: "012345",
      Message: "Payment for software license",
      InternalMemo: "Verify license agreement",
      ExchangeRate: 1.65
    }
  ]